
services:

  database:
    image: 'postgres:latest'
    container_name: db-citronix
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-net

  app:
    container_name: citronix
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
     - app-net
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

networks:
  app-net:
    driver: bridge

volumes:
  postgres_data: